services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tarea2_frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend/src:/app/src
    command: npm run dev -- --host 0.0.0.0 --port 80